import Head from "next/head";
import { Input } from "@material-tailwind/react";
import Container from "../components/Container";

import React from "react";

const Login = () => {
  return (
    <Container>
      <Head>
        <title>Airbnb</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo-4.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300&display=swap" rel="stylesheet" />
      </Head>

      <div className="relative flex flex-col w-2/4 h-screen bg-cream-airbnb ">
        <div className="w-full h-full flex items-center justify-center ">
          <img src="/logo-1.png" alt="" className="w-3/4" />
        </div>
      </div>
      <div className="flex flex-col w-full h-screen bg-pink-airbnb">
        <div className="flex h-screen justify-center items-center">
          <div className="flex flex-col justify-center w-[450px]">
            <form className="w-full mx-auto rounded-lg bg-white p-8 px-8 h-[500px]" onSub>
              <h2 className="text-[40px] text-center text-pink-airbnb font-bold">Login</h2>
              <p className="text-[20px] text-center text-black-airbnb font-semibold mt-7 mb-7">Where is Your Next Home?</p>
              <div className="flex flex-col py-2 mt-5">
                <Input variant="outlined" size="lg" label="Email" type="email" className="text-black-airbnb" />
              </div>
              <div className="flex flex-col py-2 mt-5">
                <Input variant="outlined" size="lg" label="Password" type="password" className="text-black-airbnb" />
              </div>
              <div className="flex justify-end py-2">
                <a href="">
                  <p className="text-pink-airbnb hover:text-[#E75056]">Sign Up</p>
                </a>
              </div>
              <button type="submit" className="w-[90%] flex m-auto mt-6 py-2 bg-pink-airbnb shadow-lg border-none text-white text-[24px] normal-case font-semibold rounded-lg btn hover:bg-[#E75056]">
                Login
              </button>
            </form>
          </div>
        </div>
      </div>
    </Container>
  );
};

export default Login;
