import Head from 'next/head'
import Container from '../component/Container'

export default function Home() {
  return (
    <Container>
      <Head>
        <title>Airbnb</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo-4.png" />
      </Head>

      <div>
        <p className='text-5xl text-pink-airbnb'>haloo</p>
      </div>
      
    </Container>
  )
}
