import React from 'react'
import Layout from '../components/Layout'
import Head from 'next/head'
import Container from '../components/Container'

function RegisterForm() {
  return (
    <Container>
      <Head>
        <title>Airbnb</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo-4.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300&display=swap" rel="stylesheet" />
      </Head>
      <div className='grid grid-cols-4 w-full h-screen'>
        <div className='col-span-1 bg-pink-airbnb w-full h-full flex items-center justify-center'>
          <img src="/logo-2.png" alt="" className="w-3/4" />
        </div>
        <div className='w-[90%] bg-[#FBFBFB] flex items-center justify-center rounded-lg m-6 col-span-3'>
          <form class="w-[90%] justify-center items-center align-middle">
            <div class="md:flex md:items-center mb-6">
              <div class="md:w-[25%]">
                <label class="block text-pink-airbnb font-semibold text-2xl md:text-left mb-1 md:mb-0 pr-4" for="inline-full-name">
                  Full Name
                </label>
              </div>
              <div class="md:w-[75%]">
                <input class="bg-gray-200 appearance-none border-2 border-[#D9D9D9] rounded-2xl w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-pink-airbnb h-14" id="inline-full-name" type="text" placeholder='your name here' />
              </div>
            </div>
            <div class="md:flex md:items-center mb-6">
              <div class="md:w-[25%]">
                <label class="block text-pink-airbnb font-semibold text-2xl md:text-left mb-1 md:mb-0 pr-4" for="inline-email">
                  Email
                </label>
              </div>
              <div class="md:w-[75%]">
                <input class="bg-gray-200 appearance-none border-2 border-[#D9D9D9] rounded-2xl  w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-pink-airbnb h-14" id="inline-email" type="text" placeholder='your email here' />
              </div>
            </div>
            <div class="md:flex md:items-center mb-6">
              <div class="md:w-[25%]">
                <label class="block text-pink-airbnb font-semibold text-2xl md:text-left mb-1 md:mb-0 pr-4" for="inline-password">
                  Password
                </label>
              </div>
              <div class="md:w-[75%]">
                <input class="bg-gray-200 appearance-none border-2 border-[#D9D9D9] rounded-2xl  w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-pink-airbnb h-14" id="inline-password" type="text" placeholder='********' />
              </div>
            </div>
            <div class="md:flex md:items-center flex justify-end">
              <button class="shadow bg-pink-airbnb hover:bg-[#DF5A60] focus:shadow-outline focus:outline-none text-white font-bold py-2 px-12 rounded" type="button">
                Sign Up
              </button>
            </div>
          </form>
        </div>
      </div>

    </Container>

  )
}

export default RegisterForm